version: '3.4'

services:
    redisdb:
        image: redis

    redistemplate.api:
        image: ${DOCKER_REGISTRY-}redistemplateapi
        build:
                context: .
                dockerfile: RedisTemplate.API/Dockerfile
